name: security-actions

on:
  workflow_dispatch:

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 
        with:
          java-version: 1.8

      - name: Build with Maven
        working-directory: ./app/
        run: |
          mvn clean package
          ls -l ./target

      - name: save artifact
        uses: actions/upload-artifact@v3
        with:
          name: scan-target
          path: app/target/verademo.war