name: security-actions

on:
  workflow_dispatch:

jobs:
  build:
    name: checkout
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3 
   
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1 
      with:
        java-version: 1.8

    - name: build maven
      run: |
        cd ./app
        mvn clean package install
        pwd
        ls -l ./target