name: security-actions-dev

on:
  workflow_dispatch:

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get app id
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VKEY }}
        run: |
          sudo apt-get install python3-pip httpie jq -y
          pip3 install veracode-api-signing
          http --auth-type=veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=m3academy-java-web" | jq '._embedded.applications | .[].id'

