name: security-actions

on:
  workflow_dispatch:

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1 
        with:
          java-version: 1.8

      - name: Build with Maven
        working-directory: ./app/
        run: |
          mvn clean package
          ls -l ./target

      - name: save artifact
        uses: actions/upload-artifact@v4
        with:
          name: scan-target
          path: app/target/verademo.war

  veracode-sca-scan:
    name: veracode sca scan
    runs-on: ubuntu-latest
    needs: [ checkout-and-build ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v4
      
      - name: Run SCA Scan
        env:
          SRCCLR_API_TOKEN: ${{ secrets.SRCCLR_API_TOKEN }}
        run: |
          curl -sSL https://download.sourceclear.com/ci.sh | sh -s scan --update-advisor --uri-as-name
  
  veracode-sast-policy-scan:
    name: veracode policy scan
    runs-on: ubuntu-latest
    needs: [ checkout-and-build ]
    
    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        
      - name: get archive
        uses: actions/download-artifact@v4 
        with:
          name: scan-target

      - name: list artifact
        run: |
          pwd
          ls -l

      - name: upload and scan 
        uses: veracode/veracode-uploadandscan-action@0.2.7
        with:
          appname: 'm3academy-java-web'
          createprofile: true
          teams: 'M3Academy'
          filepath: 'verademo.war'
          vid: '${{ secrets.VID }}'
          vkey: '${{ secrets.VKEY }}'
          version: "${{ github.run_id }}"
          scantimeout: 0
          criticality: 'High'