name: security-actions-dev

on:
  workflow_dispatch:

jobs:
  checkout-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: checkout code
        uses: actions/checkout@v4

      - name: get app id
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VKEY }}
        run: |
          sudo apt-get install python3-pip httpie jq -y
          pip3 install veracode-api-signing
          
          APPID=$(http --auth-type=veracode_hmac GET "https://api.veracode.com/appsec/v1/applications/?name=m3academy-java-web" | jq '._embedded.applications | .[].id')
          echo ${APPID}

      - name: get app id via wrapper
        env:
          VERACODE_API_KEY_ID: ${{ secrets.VID }}
          VERACODE_API_KEY_SECRET: ${{ secrets.VKEY }}
        run: |
          curl -o veracode-wrapper.jar https://repo1.maven.org/maven2/com/veracode/vosp/api/wrappers/vosp-api-wrappers-java/24.10.15.0/vosp-api-wrappers-java-24.10.15.0.jar
          APPID=$(java -jar veracode-wrapper.jar -vid ${VERACODE_API_KEY_ID} -vkey ${VERACODE_API_KEY_SECRET} -action getapplist | grep "m3academy-java-web" | grep -Po 'app_id="\K.*?(?=")')
          echo ${APPID}